apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  # Data to be replicated into OPA
  sync:
    syncOnly:
      - group: "storage.cnrm.cloud.google.com"
        version: "v1beta1"
        kind: "StorageBucket"
  validation:
    # Requests for which we want to run traces
    traces:
        # The requesting user for which traces will be run
      - user: "kelsey.hightower@gmail.com"
        kind:
          # The group, version, kind for which we want to run a trace
          group: "storage.cnrm.cloud.google.com"
          version: v1beta1"
          kind: "StorageBucket"
          dump: "All"
